
export const countries = [
    "global",
    "algeria",
    "argentina",
    "australia",
    "austria",
    "azerbaijan",
    "belarus",
    "belgium",
    "brazil",
    "bulgaria",
    "cameroon",
    "canada",
    "chile",
    "china",
    "colombia",
    "costa rica",
    "croatia",
    "czech republic",
    "côte d'ivoire",
    "denmark",
    "egypt",
    "finland",
    "france",
    "germany",
    "ghana",
    "greece",
    "hungary",
    "india",
    "indonesia",
    "ireland",
    "israel",
    "italy",
    "japan",
    "kazakhstan",
    "kenya",
    "malaysia",
    "mexico",
    "morocco",
    "mozambique",
    "netherlands",
    "new zealand",
    "nigeria",
    "norway",
    "peru",
    "philippines",
    "poland",
    "portugal",
    "romania",
    "russia",
    "saudi arabia",
    "senegal",
    "singapore",
    "south africa",
    "south korea",
    "spain",
    "sweden",
    "switzerland",
    "tanzania",
    "thailand",
    "tunisia",
    "turkey",
    "uganda",
    "ukraine",
    "united arab emirates",
    "united kingdom",
    "united states",
    "uruguay",
    "uzbekistan",
    "venezuela",
    "vietnam",
    "zambia"
]

export const countriesISO = {
    "global": "", // Not applicable for ISO code
    "algeria": "DZ",
    "argentina": "AR",
    "australia": "AU",
    "austria": "AT",
    "azerbaijan": "AZ",
    "belarus": "BY",
    "belgium": "BE",
    "brazil": "BR",
    "bulgaria": "BG",
    "cameroon": "CM",
    "canada": "CA",
    "chile": "CL",
    "china": "CN",
    "colombia": "CO",
    "costa rica": "CR",
    "croatia": "HR",
    "czech republic": "CZ",
    "côte d'ivoire": "CI",
    "denmark": "DK",
    "egypt": "EG",
    "finland": "FI",
    "france": "FR",
    "germany": "DE",
    "ghana": "GH",
    "greece": "GR",
    "hungary": "HU",
    "india": "IN",
    "indonesia": "ID",
    "ireland": "IE",
    "israel": "IL",
    "italy": "IT",
    "japan": "JP",
    "kazakhstan": "KZ",
    "kenya": "KE",
    "malaysia": "MY",
    "mexico": "MX",
    "morocco": "MA",
    "mozambique": "MZ",
    "netherlands": "NL",
    "new zealand": "NZ",
    "nigeria": "NG",
    "norway": "NO",
    "peru": "PE",
    "philippines": "PH",
    "poland": "PL",
    "portugal": "PT",
    "romania": "RO",
    "russia": "RU",
    "saudi arabia": "SA",
    "senegal": "SN",
    "singapore": "SG",
    "south africa": "ZA",
    "south korea": "KR",
    "spain": "ES",
    "sweden": "SE",
    "switzerland": "CH",
    "tanzania": "TZ",
    "thailand": "TH",
    "tunisia": "TN",
    "turkey": "TR",
    "uganda": "UG",
    "ukraine": "UA",
    "united arab emirates": "AE",
    "united kingdom": "GB",
    "united states": "US",
    "uruguay": "UY",
    "uzbekistan": "UZ",
    "venezuela": "VE",
    "vietnam": "VN",
    "zambia": "ZM"
};


export const genres = [
    "POP",
    "HIP_HOP_RAP",
    "DANCE",
    "ELECTRONIC",
    "RNB_SOUL",
    "ALTERNATIVE",
    "ROCK",
    "LATIN",
    "FILM_TV_STAGE",
    "COUNTRY",
    "AFRO_BEATS",
    "WORLDWIDE",
    "REGGAE_DANCE_HALL",
    "HOUSE",
    "K_POP",
    "FRENCH_POP",
    "SINGER_SONGWRITER",
    "REGIONAL_MEXICANO"
]